[package]
name = "gofish"
version = "0.1.0"
authors = ["John Brehm <cooljohnny3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"

[dev-dependencies]
mockiato = "0.9.5"